@startuml withdraw

title "Withdraw"

actor "NolimitCity" as NolimitCity

participant "NolimitCityController" as NolimitCityController
participant "BetHandler" as BetHandler
participant "TransactionManager" as TransactionManager
participant "TransactionService: gRPC" as TransactionService
participant "TransactionBatchManager" as TransactionBatchManager
participant "TransactionBatchService: gRPC" as TransactionBatchService
participant "SessionContextManager" as SessionContextManager
participant "SessionContextService: gRPC" as SessionContextService

!include Withdraw-flow.wsd

@enduml